---
title: "Other Klayout Functions"
author: "Scott Alder"
date: "8/24/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(results = "hold")
```

```{r} 
library(reticulate)
library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library(rgdal)
library(broom)
library(magick)
```

# Create dummy data

```{python results='hide'}
#### Python Code Chunk ####
import pya # "pya" is the actual module name, not "klayout"

# Create dummy layout data
layout = pya.Layout()
top = layout.create_cell("TOP")
l1 = layout.layer(1, 0)

# Repetition
x_reps = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
y_reps = [1,2,3,4,5,6,7,8,9,10]
dims = [1000, 2000]
sep  = [100, 200]

for xr in x_reps:
  for yr in y_reps:
    top.shapes(l1).insert(
      pya.Box(
        0.0     + (xr - 1)*(sep[0] + dims[0]), # Left
        0.0     + (yr - 1)*(sep[1] + dims[1]), # Bottom
        dims[0] + (xr - 1)*(sep[0] + dims[0]), # Right
        dims[1] + (yr - 1)*(sep[1] + dims[1])  # Top
      )
    ) 
    
# Save as *.oas file
layout.write("test2.oas")
layout.write("test2.dxf")
```

```{r}
#### R Code Chunk ####
layout_data <- 
  readOGR("test2.dxf") %>% 
  tidy() %>% 
  rename(x=long, y=lat)
```

```{r}
theme_set(theme_bw())
g <- 
  layout_data %>% 
  ggplot(aes(x, y, group=group)) +
  geom_polygon(fill="black", color=NA) +
  coord_fixed() +
  scale_x_continuous(n.breaks = 10) +
  scale_y_continuous(n.breaks = 10)

print(g)
```

# Clipping

```{python}
import pya
layout = pya.Layout.new()
layout.read("test2.oas")

top_cell = layout.cell("TOP")

bb_array = [
  pya.Box.new(2000, 2500, 7000, 7500),
  pya.Box.new(12000, 12500, 15000, 15500)
]

clipped_layout = pya.Layout.new()
clipped_layout.dbu = layout.dbu
for layer_id in layout.layer_indices():
  clipped_layout.insert_layer_at(layer_id, layout.get_info(layer_id))
  
clip_cells = layout.multi_clip_into(top_cell.cell_index(), clipped_layout, bb_array)  

clip_top_cell = clipped_layout.create_cell("TOP")  
for cc in clip_cells: 
  clip_top_cell.insert(pya.CellInstArray(cc, pya.Trans()))

clipped_layout.write("clipped_test2.oas")
clipped_layout.write("clipped_test2.dxf")
```


```{r}
theme_set(theme_bw())
g <- 
  readOGR("clipped_test2.dxf") %>% 
  tidy() %>% 
  rename(x=long, y=lat) %>% 
  ggplot(aes(x, y, group=group)) +
  geom_polygon(fill="black", color=NA) +
  coord_fixed() +
  scale_x_continuous(n.breaks = 10) +
  scale_y_continuous(n.breaks = 10)

print(g)
```

# Image capture

```{r}
knitr::knit_engines$set(lym = function(options) {
  # the source code is in options$code; just do
  # whatever you want with it
  lym_code <- paste(options$code, collapse = "\n") #glue::glue(options$code)
  ly_file <- options$layout_file
  
  tmp_py <- tempfile(fileext=".py")
  writeLines(lym_code, tmp_py)
  
  klayout_exe_path <-
    Sys.getenv("USERPROFILE") %>%
    paste0("\\AppData\\Roaming\\") %>%
    list.files("klayout_app.exe", recursive = T, full.names = T) %>%
    normalizePath()
  
  print(klayout_exe_path)
  print(ly_file)
  print(lym_code)
  
  # `<path to klayout_app.exe> <path to layout file> -r <path to Python script>`
  lym_output <- 
    paste(klayout_exe_path, ly_file, "-r", tmp_py) %>% # -r prevents GUI from opening
    system(intern=TRUE)
})
```

```{lym layout_file="test2.oas"}
import os

# A list of coordinates (x, y) in micrometers, the window size (micrometers)
# and the name of the file to produce
coords = [
  [4.5,   9.5, 5.0, "img1.png"],
  [14.5, 17.5, 5.0, "img2.png"]
  # more ...
]

# Image resolution
width  = 400
height = 400

# Output directory (please change)
# out = "/home/matthias/screenshots"

lv = pya.LayoutView.current()

# lv.load_layer_props("<path to lyp file>")
# lv.set_layer_properties(<lyp settings?>)
lv.set_config("grid-visible", "false")

for cspec in coords:

  (x, y, dim, fn) = cspec

  center = pya.DPoint(x, y)
  dv = pya.DVector(dim * 0.5, dim * 0.5)
  lv.zoom_box(pya.DBox(center, center).enlarged(dv))

  # fn_path = os.path.join(out, fn)
  print("Saving image for position " + str(center) + " to " + fn)

  lv.save_image(fn, width, height)
```

```{r}
image_read("img1.png") %>% 
  plot()

image_read("img2.png") %>% 
  plot()
```


# Coordinate transformations

```{python}
import pya
layout = pya.Layout.new()
layout.read("test2.oas")

# The sequence of operations is: magnification, mirroring at x axis,
#   rotation, application of displacement.
# @param mag The magnification
# @param rot The rotation angle in units of degree
# @param mirrx True, if mirrored at x axis
# @param x The x displacement
# @param y The y displacement
t = pya.CplxTrans.new(20.0, 90, True, -30.0, 20.0)

layout.transform(t.to_trans())

layout.write("trans_test2.dxf")
```

```{r}
theme_set(theme_bw())
g <- 
  readOGR("trans_test2.dxf") %>% 
  tidy() %>% 
  rename(x=long, y=lat) %>% 
  ggplot(aes(x, y, group=group)) +
  geom_polygon(fill="black", color=NA) +
  coord_fixed() +
  scale_x_continuous(n.breaks = 10) +
  scale_y_continuous(n.breaks = 10)

print(g)
```

# Combine files

```{python results='hide'}
#### Python Code Chunk ####
import pya # "pya" is the actual module name, not "klayout"

# Create dummy layout data
layout = pya.Layout()
top = layout.create_cell("TOP")
l1 = layout.layer(2, 0)

# Repetition
origin = [0, 1000]
x_reps = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
y_reps = [1,2,3,4,5,6,7,8,9,10]
dims = [1000, 200]
sep  = [100, 2000]

for xr in x_reps:
  for yr in y_reps:
    top.shapes(l1).insert(
      pya.Box(
        origin[0] + 0.0     + (xr - 1)*(sep[0] + dims[0]), # Left
        origin[1] + 0.0     + (yr - 1)*(sep[1] + dims[1]), # Bottom
        origin[0] + dims[0] + (xr - 1)*(sep[0] + dims[0]), # Right
        origin[1] + dims[1] + (yr - 1)*(sep[1] + dims[1])  # Top
      )
    ) 
    
# Save as *.oas file
layout.write("test3.oas")
layout.write("test3.dxf")
```

```{r}
theme_set(theme_bw())
g <- 
  ggplot(data.frame(), aes(x, y, group=group)) +
  # geom_polygon(
  #   data = 
  #     readOGR("test2.dxf") %>% 
  #       tidy() %>% 
  #       rename(x=long, y=lat),
  #   fill="red", color=NA
  # ) +
  geom_polygon(
    data = 
      readOGR("test3.dxf") %>% 
      tidy() %>% 
      rename(x=long, y=lat),
    fill="black", color=NA
  ) +
  coord_fixed() +
  scale_x_continuous(n.breaks = 10) +
  scale_y_continuous(n.breaks = 10)

print(g)
```

```
#### Python Code Chunk ####
import pya # "pya" is the actual module name, not "klayout"

# Create dummy layout data
layout_2 = pya.Layout()
layout_2.read("test2.oas")
layout_3 = pya.Layout()
layout_3.read("test3.oas")

# layout_4 = pya.Layout()
# layout_4.insert_layer_at(layout_2.layer_indices())
# layout_4.insert_layer_at(layout_3.layer_indices())

merged_layout = pya.Layout.new()
merged_layout.dbu = layout_2.dbu # assume 2 and 3 have equal DBU

# Layers
for layer_id in layout_2.layer_indices():
  merged_layout.insert_layer_at(layer_id, layout_2.get_info(layer_id))

for layer_id in layout_3.layer_indices():
  merged_layout.insert_layer_at(layer_id, layout_3.get_info(layer_id))
  
# Cells
# clip_cells = layout.multi_clip_into(top_cell.cell_index(), clipped_layout, bb_array)  
cells_2 = layout_2.each_cell()
cells_3 = layout_3.each_cell()

merged_top_cell = clipped_layout.create_cell("TOP")
for cc in clip_cells:
  merged_top_cell.insert(pya.CellInstArray(cc, pya.Trans()))
  

# top_cell = layout.cell("TOP")
# 
# bb_array = [
#   pya.Box.new(2000, 2500, 7000, 7500),
#   pya.Box.new(12000, 12500, 15000, 15500)
# ]
# 
# clipped_layout = pya.Layout.new()
# clipped_layout.dbu = layout.dbu
# for layer_id in layout.layer_indices():
#   clipped_layout.insert_layer_at(layer_id, layout.get_info(layer_id))
#   
# clip_cells = layout.multi_clip_into(top_cell.cell_index(), clipped_layout, bb_array)  
# 
# clip_top_cell = clipped_layout.create_cell("TOP")  
# for cc in clip_cells: 
#   clip_top_cell.insert(pya.CellInstArray(cc, pya.Trans()))
# 
# clipped_layout.write("clipped_test2.oas")
# clipped_layout.write("clipped_test2.dxf")

```










